merged wait_for_emulator with .travis.yml
Lazy mans fix for a permission error.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -33,6 +33,21 @@ before_script:
     # Create and start emulator
     - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
     - emulator -avd test -no-skin -no-audio -no-window &
-    - wait_for_emulator
+    - set +e
+    - bootanim=""
+    - failcounter=0
+    - until [[ "$bootanim" =~ "stopped" ]]; do
+    - bootanim=`adb -e shell getprop init.svc.bootanim 2>&1`
+    - echo "$bootanim"
+    - if [[ "$bootanim" =~ "not found" ]]; then
+    - let "failcounter += 1"
+    - if [[ $failcounter -gt 15 ]]; then
+    - echo "Failed to start emulator"
+    - exit 1
+    - fi
+    - fi
+    - sleep 1
+    - done
+    - echo "Done"
     
 script: mvn install -Pintegration-tests -Dandroid.device=test
